apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  template:
    metadata:
      name: app-db-secret
      labels:
        {{- include "my-app-chart.labels" . | nindent 8 }}