apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- if eq .Values.appConfig.environment "production" }}
    DB_PASSWORD: AgA7WJSV/dzmhrSkUMkMXXlAMNW7UM7vmd+gVEzJcj82ivOVoCyAjG0e6Tr5igyE6CcIN6htMX5qVimS0npM+w60JvEdfeRAUWeDKJtadK1l3mwambjz3eSfBT9rlSqRXDH6y6+7oNBKMIfNRa0k4QPDTCZ7YQEYLHbK4hGq3iBYkcVa8HhYfpP15whcGEqNU6h3UwFigZp+etP/JTBWEQyWACO5hqYG9EGzYM0qICki7oFl0gwHTUsusD/dQMU594bbNhgj8b3MBGzjpg57RZvr359N9bXZSg/reoFLn7YjOoQ12AdUMkvXUxy06GGyRlLSirNxNiI52mzGHrhrvoVtIUTdr8HDSyQDYvlM0SlQMQrQZ/Zh+NeVAgksCto2djG2yxIw05rmfz/OlAdmh46zC0cYDZk8li1aA2D0pzsMmcWunRGr6gdDmcKygZIwdUVRahJII8ipKo84WN1fb4T5yIi7gNlh4ogNAiVmHHM5mX346A8a25Lmjy8/GLxBRLzso9Aw85TXVZCvkblR4DlzIc2vOce97+XipbBAgqxLohMvT8tsXpQWo0IgPmJPss9jLN/rNYJt87gKYGSVOCBeIn9o6ox5IWa2LMpIarTH+Ewxr7q8rxov2qdG9UTW3I9KsfMcDJ/agGC6JN0d8es/UABHIhDnspxOZxxW/iSpAhMiBZt0Tloo5szeXaGoJyzFJbimU9Tbr3b05rBeNwy5XdvMJHdEEJVj9dReHaWKz0oU
    {{- else }}
    DB_PASSWORD: AgCT6rNFI2kCEupC4xO3opqTmZklH+8+fNxBjAwNJVZ4IKSfgsY0D1W68ajfdEm9fBaO9gnRPHm9Dj8BFcvrt3kjs0vR0htFNX0TxQeJyypvUQizXrBwSlYNbvlPwT2TGmxTs3AeZmDcodC7/N1fWFYZBs8zWalqCfC9MrjulwgVTgYAhEfTNCNG6uQ5uhSktpJ43L0jfQkSjMvT7Zsku+y3ViUprCVDKr7+TsShoM3WlrtwckvMV1kf+4n8eqvi30eoMCneq8Xd8pv/GA+8igHIP+UUpvDI7a9kXfpzn2ZQX1pBScyLzt5Poc47BPrg1yl2sIkkDhj//a7lGDSugcjQA2JwXtuqTjoXewkUyDKkev1QdzB/L9v5dUZyJQuZq1MWFmfqU5DkcctrDsNglcW9Q4195MRAzbdnck/IiVK3TPZHSOYM22wkI0NosOXo5J8iUbx/swqjkgTVCZwxjD8uvNMIEwx4JkP9rQrrh7HM8L9FLaLCe1CU/szUG37+19iGTovdelaNzpxxENQmO5CE6pFOriiBmgj+Kmz4rDHN+QGmqISqMcdg7SQca50reNfTckreOafKvdI1T2DuMvF+4U6cTnA7uXoNHWpmH5lNSQoLasWLQj/U7hht3pU2NeQj7FmXVd2xC3AitRtbPtRZvFBOctj5My3LepE9ApozRUYykn1O3ohWqcZ6rzc8x7VZCKMbC0+o75O+WgrSCDDn/CrD8R30KpLVp2FO
    {{- end }}
  template:
    metadata:
      name: app-db-secret
      labels:
        {{- include "my-app-chart.labels" . | nindent 8 }}