apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- if eq .Values.appConfig.environment "production" }}
    DB_PASSWORD: AgCt0RFWxTJRQGn0scUrRzLJqXTWkevUCxBIBp18w3ItzXGhJFhhDWYxBGSaDVBFvhgwjSbcanIkMsZN7OWER5Q/NAXGTrDfs9tQdqEwNoVFBDxouZXWJ0e1O46bJ2Yr3kw8nFRDfAeSXOg3Hza1s0B7tBitxyb6Oc65wfJ0ZBoAI7dXiv8jv6lDNshocdV7OnrlOinoKGLIWUfUeDGiFid0dnMGrqHVuDTUY+i9dKQFh71KyAnuLhfwAad1v/imgXR7+FPLSsA51nbKMSSdsfh3WyHe3gOxqhBjiKIzHsBaWpq/tU4KcB7LZgiupy0vq0q2bpH4no+Bnerp9ykGII5qekS/sY8clOliWZqS0/wNoP0J7NMyFi9WEHWgXfJaOUwcyeRBd+2zZETO6RdM9eL/QFDPnpLdcJ5/guEgJ4mRgaocUriEypd+4RsW+u/+j5LgRb9RZ5dlNEfLT4YpEkhuDB0lHagHhjrWwySrVDVMbMb1UA5N0X4lCVF4NR8ukDS8OBddM10v+pd33Jx281zxpFxfqDVatfJlOsiJmBofYX1djYnubQiviGBtd0roF58ka76TU45dTZqmm6TctOG4DEB9tWXgAFLoNek5uxkITD8I6BWSUcR5tQHepvNVNaNo4OLLaV8wNd9kLTDJfx+SjmqJ4SbIP4RgTTYTmYLCLUfivYlNS+cI16V8pRUWGwOK2OPTTHA5CQjcvWRkduR32KyYGcrUthCft+15VN2bgg==
    {{- else }}
    DB_PASSWORD: AgBu3LVZ/syHXTO3DT29EwtVDYfyaF5Frh4r0FqYqbh2svR1FZNvrcIrLWPcAPjfmKKvPTFJL1baUpwEpZDLzIOvJsWs35lIzGZKLjbaRBRg5F9ChZ1w78RMeGs6Mfacy5/JhFFo+VBu+wNYilN8axIutu1NjAcTyx2Dq3PTJEvqmfWkuFQa7OSeHfi7wdwb577YATFz4s5Z7Vs0w9ur6ONDpyJklCICb8kETzONZqpMGmY5nbLnEu1KFX2FUt4GG+F/wGJDqF9GrSPSgR8bqx/B/MnbfXotT9MOhfOG+Sea7XI9abwxHviZ0JVGjEsqdE22O5Y8dt3tdOpxyKgL5FLITH75hltCZCvYa7r3TPKtOjCdDsSpdtld9I9CYB23sfnmk2d3BIlvhpAjWipI8NdSZ4LgMYF2BySzEBSV6SAWUy5rLsvXp8oNUKIS+IBfkI/1NnWxsCoZmfZXjIHW+YARMTjsNSXNujn5z9C3XJHbUIUE0J77X7DxOii67FadTNSFkk08t2AsR6HNf3/izbERF9SMnRwAvVXL5wtcU86vonFFibSSivF7J4ooVg4DDCd4wS5SqY1NKTYS/ChvWwA4ReFdEl3VsidMV1CBmBm3CQm122Yt5L0d8cAZdMeH5FTv1uaMZ8mh5hx1hLU6dFkh7YrZCEVQskFsrqfw3AGI6/Rogl1xwDIfdEypFwvviwgbumrX5ZCsQmngC/HZfhA1kteJif4Z5qWxpQ==
    {{- end }}
  template:
    metadata:
      name: app-db-secret
      labels:
        {{- include "my-app-chart.labels" . | nindent 8 }}