replicaCount: 1

appConfig:
  greeting: "Welcome to the Development Sandbox"
  environment: "development"

ingress:
  enabled: true
  hosts:
    - host: dev.app.192.168.1.53.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

secrets:
  dbPassword: "AgCxCurA0+GMSrnX/w9CRe/U8sCMi1JIgOBzgCZWyTnKvzqxVBaMIQCptmQKY1Gs0mzfPtChdBX/uOB9kk4iNe8gOPMZ3cK+7q9ycSM83l4eO7XbLBALwX1gduAx6bq/FgDjqwtb/GPCcBHrjXWlNN5fGUr3dLhULrNBSSrsgBDdfwXYU6IGtiUdf9Fc70JkCg5563fz+8oa++Eao+TfOb9vmYvRWmTP/pBoq9lYuRE3PMEqP2/kXyQl35LPBcJPFcy/3KQxj7IOm5L9XTk/pYGpkpv35OzyJZg1DtTCx6ph8Q775O9CP62nEp6vGxIVVyKYoZcAoQFBSHioDyjeLta7O5iY7yvFGjBxQB1tZNNUfEew0MsHIEOcivblaFcJWLrvTGdlTopE1Wg28bWljneePkxN5ijR/U26eHokAY1fpG+xkjiCgGk6powAIrjKXjx26fxDtRHsr+3Rc7mb+rkWVK10W/gOXDNLJeYqoZ5hvUZEftssZ8d4IuehV4dE16jBBZGi/byuNV0RN7J5NwZaxGk9C55JOHfny+RUVxYqD5ez0ZhWQuHRNRj2J+9/drc43SMcgEXyZt/u2k5MPxuI6mowZxrb8nRdNcyTAXaAyR4XWii4GRPJDRPimJ7g+mNevazoXIxU5i796O6h6zIG4HQFKdSAnwWZ88CrUDq0C7NxavCGbDLPNDrabQnp9BDeGTj24qGSo/kk6NfjRatTJ9FPIq+DmRP8zQ=="
