replicaCount: 3

appConfig:
  greeting: "Welcome to the Production System"
  environment: "production"

ingress:
  enabled: true
  hosts:
    - host: prod.app.192.168.1.53.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

secrets:
  dbPassword: AgAFdpZEenPOsqNfW+MuXI6Xbsieinj1+FlbDNsVTTaQsD8p2KcCrBEuhSXS/L4Uhp0coPFCPUvzT5L+I4S93mSX2WmwoI/XSZtctn0N9UVALgwiMR1qAqDze9d5veskVBoslDkd1mQ0fo4rLsMt/EwLWNEJJz8QoxOPGBMknIjDtTA1KY7fB+j4Ppl7QPJF7YCzn+yy/zc13096g7pnSaDfFABgBfK1brAnp6v3AiIBkII4MMMizi87rbXMyypH25cTK+S3TQsdei0DhnVhjakohwcm8yX+rirMSEVKWYHQRcBY1h1HsPYGgOuBRaQoZKtAdNty4e2fura1rpO1q0x2McK9rGhE7j0BwsQfryR739Yy5uYqIpI+/iEtYr31Mbh8B2ZGqkXwj67tEDEhUaPjpTg1L+s8pKem6RUuzZsOOQt/rYU6J2nH6j0uSVjSFAA5vOpn7vOPPA9ARSfpnVN9RqAWEtwre5dgaU+4Ak9LEfR8sQUACYeaT9dZb6tJ5rHGJ0at7v7ZANAl1ZTJ7+/I/UoHN1HAZpG+GuLfukmOPRAEZ8EGkmzP64Hi+/M/X5DSEYdmBHHYzVD/sROuLMBMwLqsqpkyRKe5MPbm3w4BbciUx0BSQYSvVB3c2YATMqdlWeSkSRGfepHc/+DTT09o1EUHazUi08gdRaGbzWXAnkqkCdfT1kdeZ4nmcTYz54jD0TAmN+RSNFHJu2/h7s9nvWsZ5kHt0/V3eHaUxcSBAg==
