#replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50

appConfig:
  greeting: "Welcome to the Production System"
  environment: "production"

ingress:
  enabled: true
  hosts:
    - host: prod.app.192.168.1.53.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

secrets:
  dbPassword: "AgBCmP8D+CIngQvbMv8DxwOgK92hl386d+SmvZV1YxO8p9pFDVanpTVY5Ba0WH3ImwPVEG+N3n3IYID20g5qEjhsjjbDjdNgJy4YvPs01ihE++E9lf6lO0m3LfEc2cmWkptMFjZgzwMykP+Q32g9TxMmoLfTiXHmayJi+M8nzfU277PfNUHtt9inh/tMhozA5Dg30NJ2wYRiToabAUPu6MEufwDdyqM61or+/oE4+/ioSPo6ayfB8GM9irP/Dy66cKrbmlDH2LVhRqzeKWYskZVhfhaPm4Gv82xmARZIa5GYojf1whyuK7fECFnqaOECOzxrSYe8DjkZP9CFzUK36J9f+C4hHw10VE9DBwqSbl7Xe7eU0gMiyrF8jkBS4cWHAA4hc+DyhW++XQHMjoJuazoowVS2Ea/G9krUmBkrUrTp+Z8sNGpbudP726xFj702meh0FFXQD5bZcjilhnkChiEJDBx6IvcrNKGNi54SI1iPxTpl9dsx1XOPQMvVjcb5CWlAXMGBpJNBnkJwcdnJTOiJmoIH4WqKGNVleSJtKd49LZLxX7WQq77+ygCC7qRGvy5sbNEWgTyK2bqOdKl5CKQj7jhSmAIrgluwRxR/EPxfCciYU+0+ymlptUDf0i6qKicnCSOKLLoeiP8D4rmQ8A871EUINqhGy++nRM3B12X10lDT9cMpWursgqsUUvMkHwSQMbsnSzdkrZpx+Qq8z3vF6q2nExSuzvSQWP8cZBYEeA=="
