replicaCount: 1

appConfig:
  greeting: "Welcome to the Development Sandbox"
  environment: "development"

ingress:
  enabled: true
  hosts:
    - host: dev.app.192.168.1.53.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

secrets:
  dbPassword: AgBu3LVZ/syHXTO3DT29EwtVDYfyaF5Frh4r0FqYqbh2svR1FZNvrcIrLWPcAPjfmKKvPTFJL1baUpwEpZDLzIOvJsWs35lIzGZKLjbaRBRg5F9ChZ1w78RMeGs6Mfacy5/JhFFo+VBu+wNYilN8axIutu1NjAcTyx2Dq3PTJEvqmfWkuFQa7OSeHfi7wdwb577YATFz4s5Z7Vs0w9ur6ONDpyJklCICb8kETzONZqpMGmY5nbLnEu1KFX2FUt4GG+F/wGJDqF9GrSPSgR8bqx/B/MnbfXotT9MOhfOG+Sea7XI9abwxHviZ0JVGjEsqdE22O5Y8dt3tdOpxyKgL5FLITH75hltCZCvYa7r3TPKtOjCdDsSpdtld9I9CYB23sfnmk2d3BIlvhpAjWipI8NdSZ4LgMYF2BySzEBSV6SAWUy5rLsvXp8oNUKIS+IBfkI/1NnWxsCoZmfZXjIHW+YARMTjsNSXNujn5z9C3XJHbUIUE0J77X7DxOii67FadTNSFkk08t2AsR6HNf3/izbERF9SMnRwAvVXL5wtcU86vonFFibSSivF7J4ooVg4DDCd4wS5SqY1NKTYS/ChvWwA4ReFdEl3VsidMV1CBmBm3CQm122Yt5L0d8cAZdMeH5FTv1uaMZ8mh5hx1hLU6dFkh7YrZCEVQskFsrqfw3AGI6/Rogl1xwDIfdEypFwvviwgbumrX5ZCsQmngC/HZfhA1kteJif4Z5qWxpQ==